# JNI bindings for Pwsh scripts. Generated by New-JniLibrary.ps1 from jni.h
# SHA-256 C88CE2CB6CE10378CD4C706A3A2AD017794AEDB9314DDCC341E39B470CDB601A (AOSP libnativehelper af5fd77f); do not edit.
# Everything is global so that callbacks invoked after Profile.ps1 returns
# (window, input) still see it. Call only on the main thread: the JNIEnv is
# activity->env (native_activity.h), which belongs to that thread.
$global:JniSlot = @{
    GetVersion = 4
    DefineClass = 5
    FindClass = 6
    FromReflectedMethod = 7
    FromReflectedField = 8
    ToReflectedMethod = 9
    GetSuperclass = 10
    IsAssignableFrom = 11
    ToReflectedField = 12
    Throw = 13
    ThrowNew = 14
    ExceptionOccurred = 15
    ExceptionDescribe = 16
    ExceptionClear = 17
    FatalError = 18
    PushLocalFrame = 19
    PopLocalFrame = 20
    NewGlobalRef = 21
    DeleteGlobalRef = 22
    DeleteLocalRef = 23
    IsSameObject = 24
    NewLocalRef = 25
    EnsureLocalCapacity = 26
    AllocObject = 27
    NewObject = 28
    NewObjectV = 29
    NewObjectA = 30
    GetObjectClass = 31
    IsInstanceOf = 32
    GetMethodID = 33
    CallObjectMethod = 34
    CallObjectMethodV = 35
    CallObjectMethodA = 36
    CallBooleanMethod = 37
    CallBooleanMethodV = 38
    CallBooleanMethodA = 39
    CallByteMethod = 40
    CallByteMethodV = 41
    CallByteMethodA = 42
    CallCharMethod = 43
    CallCharMethodV = 44
    CallCharMethodA = 45
    CallShortMethod = 46
    CallShortMethodV = 47
    CallShortMethodA = 48
    CallIntMethod = 49
    CallIntMethodV = 50
    CallIntMethodA = 51
    CallLongMethod = 52
    CallLongMethodV = 53
    CallLongMethodA = 54
    CallFloatMethod = 55
    CallFloatMethodV = 56
    CallFloatMethodA = 57
    CallDoubleMethod = 58
    CallDoubleMethodV = 59
    CallDoubleMethodA = 60
    CallVoidMethod = 61
    CallVoidMethodV = 62
    CallVoidMethodA = 63
    CallNonvirtualObjectMethod = 64
    CallNonvirtualObjectMethodV = 65
    CallNonvirtualObjectMethodA = 66
    CallNonvirtualBooleanMethod = 67
    CallNonvirtualBooleanMethodV = 68
    CallNonvirtualBooleanMethodA = 69
    CallNonvirtualByteMethod = 70
    CallNonvirtualByteMethodV = 71
    CallNonvirtualByteMethodA = 72
    CallNonvirtualCharMethod = 73
    CallNonvirtualCharMethodV = 74
    CallNonvirtualCharMethodA = 75
    CallNonvirtualShortMethod = 76
    CallNonvirtualShortMethodV = 77
    CallNonvirtualShortMethodA = 78
    CallNonvirtualIntMethod = 79
    CallNonvirtualIntMethodV = 80
    CallNonvirtualIntMethodA = 81
    CallNonvirtualLongMethod = 82
    CallNonvirtualLongMethodV = 83
    CallNonvirtualLongMethodA = 84
    CallNonvirtualFloatMethod = 85
    CallNonvirtualFloatMethodV = 86
    CallNonvirtualFloatMethodA = 87
    CallNonvirtualDoubleMethod = 88
    CallNonvirtualDoubleMethodV = 89
    CallNonvirtualDoubleMethodA = 90
    CallNonvirtualVoidMethod = 91
    CallNonvirtualVoidMethodV = 92
    CallNonvirtualVoidMethodA = 93
    GetFieldID = 94
    GetObjectField = 95
    GetBooleanField = 96
    GetByteField = 97
    GetCharField = 98
    GetShortField = 99
    GetIntField = 100
    GetLongField = 101
    GetFloatField = 102
    GetDoubleField = 103
    SetObjectField = 104
    SetBooleanField = 105
    SetByteField = 106
    SetCharField = 107
    SetShortField = 108
    SetIntField = 109
    SetLongField = 110
    SetFloatField = 111
    SetDoubleField = 112
    GetStaticMethodID = 113
    CallStaticObjectMethod = 114
    CallStaticObjectMethodV = 115
    CallStaticObjectMethodA = 116
    CallStaticBooleanMethod = 117
    CallStaticBooleanMethodV = 118
    CallStaticBooleanMethodA = 119
    CallStaticByteMethod = 120
    CallStaticByteMethodV = 121
    CallStaticByteMethodA = 122
    CallStaticCharMethod = 123
    CallStaticCharMethodV = 124
    CallStaticCharMethodA = 125
    CallStaticShortMethod = 126
    CallStaticShortMethodV = 127
    CallStaticShortMethodA = 128
    CallStaticIntMethod = 129
    CallStaticIntMethodV = 130
    CallStaticIntMethodA = 131
    CallStaticLongMethod = 132
    CallStaticLongMethodV = 133
    CallStaticLongMethodA = 134
    CallStaticFloatMethod = 135
    CallStaticFloatMethodV = 136
    CallStaticFloatMethodA = 137
    CallStaticDoubleMethod = 138
    CallStaticDoubleMethodV = 139
    CallStaticDoubleMethodA = 140
    CallStaticVoidMethod = 141
    CallStaticVoidMethodV = 142
    CallStaticVoidMethodA = 143
    GetStaticFieldID = 144
    GetStaticObjectField = 145
    GetStaticBooleanField = 146
    GetStaticByteField = 147
    GetStaticCharField = 148
    GetStaticShortField = 149
    GetStaticIntField = 150
    GetStaticLongField = 151
    GetStaticFloatField = 152
    GetStaticDoubleField = 153
    SetStaticObjectField = 154
    SetStaticBooleanField = 155
    SetStaticByteField = 156
    SetStaticCharField = 157
    SetStaticShortField = 158
    SetStaticIntField = 159
    SetStaticLongField = 160
    SetStaticFloatField = 161
    SetStaticDoubleField = 162
    NewString = 163
    GetStringLength = 164
    GetStringChars = 165
    ReleaseStringChars = 166
    NewStringUTF = 167
    GetStringUTFLength = 168
    GetStringUTFChars = 169
    ReleaseStringUTFChars = 170
    GetArrayLength = 171
    NewObjectArray = 172
    GetObjectArrayElement = 173
    SetObjectArrayElement = 174
    NewBooleanArray = 175
    NewByteArray = 176
    NewCharArray = 177
    NewShortArray = 178
    NewIntArray = 179
    NewLongArray = 180
    NewFloatArray = 181
    NewDoubleArray = 182
    GetBooleanArrayElements = 183
    GetByteArrayElements = 184
    GetCharArrayElements = 185
    GetShortArrayElements = 186
    GetIntArrayElements = 187
    GetLongArrayElements = 188
    GetFloatArrayElements = 189
    GetDoubleArrayElements = 190
    ReleaseBooleanArrayElements = 191
    ReleaseByteArrayElements = 192
    ReleaseCharArrayElements = 193
    ReleaseShortArrayElements = 194
    ReleaseIntArrayElements = 195
    ReleaseLongArrayElements = 196
    ReleaseFloatArrayElements = 197
    ReleaseDoubleArrayElements = 198
    GetBooleanArrayRegion = 199
    GetByteArrayRegion = 200
    GetCharArrayRegion = 201
    GetShortArrayRegion = 202
    GetIntArrayRegion = 203
    GetLongArrayRegion = 204
    GetFloatArrayRegion = 205
    GetDoubleArrayRegion = 206
    SetBooleanArrayRegion = 207
    SetByteArrayRegion = 208
    SetCharArrayRegion = 209
    SetShortArrayRegion = 210
    SetIntArrayRegion = 211
    SetLongArrayRegion = 212
    SetFloatArrayRegion = 213
    SetDoubleArrayRegion = 214
    RegisterNatives = 215
    UnregisterNatives = 216
    MonitorEnter = 217
    MonitorExit = 218
    GetJavaVM = 219
    GetStringRegion = 220
    GetStringUTFRegion = 221
    GetPrimitiveArrayCritical = 222
    ReleasePrimitiveArrayCritical = 223
    GetStringCritical = 224
    ReleaseStringCritical = 225
    NewWeakGlobalRef = 226
    DeleteWeakGlobalRef = 227
    ExceptionCheck = 228
    NewDirectByteBuffer = 229
    GetDirectBufferAddress = 230
    GetDirectBufferCapacity = 231
    GetObjectRefType = 232
}
$global:JniM = [Runtime.InteropServices.Marshal]
$ab = [Reflection.Emit.AssemblyBuilder]::DefineDynamicAssembly([Reflection.AssemblyName]::new('PwshJni'), [Reflection.Emit.AssemblyBuilderAccess]::Run)
$global:JniModule = $ab.DefineDynamicModule('PwshJni')
$global:JniTypes = @{}
$global:JniCache = @{}

# A delegate type per native signature (the platform C convention).
function global:Get-NativeDelegateType([type] $Return, [type[]] $Parameters) {
    $key = $Return.FullName + '(' + (@(foreach ($t in $Parameters) { $t.FullName }) -join ',') + ')'
    if (-not $global:JniTypes.ContainsKey($key)) {
        $dt = $global:JniModule.DefineType("PwshJni.D$($global:JniTypes.Count)", [Reflection.TypeAttributes]'Public,Sealed', [MulticastDelegate])
        $c = $dt.DefineConstructor([Reflection.MethodAttributes]'Public,HideBySig,SpecialName,RTSpecialName', [Reflection.CallingConventions]::Standard, [type[]]@([object], [IntPtr]))
        $c.SetImplementationFlags([Reflection.MethodImplAttributes]'Runtime,Managed')
        $i = $dt.DefineMethod('Invoke', [Reflection.MethodAttributes]'Public,HideBySig,NewSlot,Virtual', $Return, $Parameters)
        $i.SetImplementationFlags([Reflection.MethodImplAttributes]'Runtime,Managed')
        $global:JniTypes[$key] = $dt.CreateType()
    }
    $global:JniTypes[$key]
}

# P/Invoke into an NDK library, bound once per name.
$global:JniNativeType = $null
$global:JniImports = [ordered]@{}
function global:Add-NativeImport([string] $Name, [string] $Library, [type] $Return, [type[]] $Parameters) {
    $global:JniImports[$Name] = @($Library, $Return, $Parameters)
}
function global:Complete-NativeImports {
    $nt = $global:JniModule.DefineType("PwshJni.Native$([guid]::NewGuid().ToString('N'))", [Reflection.TypeAttributes]'Public,Abstract,Sealed')
    foreach ($e in $global:JniImports.GetEnumerator()) {
        $m = $nt.DefinePInvokeMethod($e.Key, $e.Value[0], [Reflection.MethodAttributes]'Public,Static,PinvokeImpl,HideBySig',
            [Reflection.CallingConventions]::Standard, $e.Value[1], $e.Value[2],
            [Runtime.InteropServices.CallingConvention]::Cdecl, [Runtime.InteropServices.CharSet]::Ansi)
        $m.SetImplementationFlags([Reflection.MethodImplAttributes]::PreserveSig)
    }
    $global:Ndk = $nt.CreateType()
}
Add-NativeImport '__android_log_write' 'liblog.so' ([int]) @([int], [string], [string])
function global:Write-AndroidLog([string] $Text, [int] $Priority = 4) { [void]$global:Ndk::__android_log_write($Priority, 'Pwsh', $Text) }

$p = [IntPtr]::Size
$global:JniActivity = [IntPtr]$NativeActivityHandle
$global:JniEnv = $global:JniM::ReadIntPtr($global:JniActivity, 2 * $p)       # callbacks, vm, env, clazz, ...
$global:JniActivityObject = $global:JniM::ReadIntPtr($global:JniActivity, 3 * $p)

# A JNI function by name, typed by its native signature.
function global:Get-Jni([string] $Name, [type] $Return, [type[]] $Parameters) {
    $key = $Name + '|' + $Return.FullName + '(' + (@(foreach ($t in $Parameters) { $t.FullName }) -join ',') + ')'
    if (-not $global:JniCache.ContainsKey($key)) {
        $table = $global:JniM::ReadIntPtr($global:JniEnv, 0)
        $fp = $global:JniM::ReadIntPtr($table, $global:JniSlot[$Name] * [IntPtr]::Size)
        $global:JniCache[$key] = $global:JniM::GetDelegateForFunctionPointer($fp, (Get-NativeDelegateType $Return $Parameters))
    }
    $global:JniCache[$key]
}

$I = [IntPtr]
$global:Jni = @{
    ExceptionCheck = Get-Jni ExceptionCheck ([byte]) @($I)
    ExceptionDescribe = Get-Jni ExceptionDescribe ([void]) @($I)
    ExceptionClear = Get-Jni ExceptionClear ([void]) @($I)
    FindClass = Get-Jni FindClass $I @($I, $I)
    GetObjectClass = Get-Jni GetObjectClass $I @($I, $I)
    GetMethodID = Get-Jni GetMethodID $I @($I, $I, $I, $I)
    GetStaticMethodID = Get-Jni GetStaticMethodID $I @($I, $I, $I, $I)
    GetFieldID = Get-Jni GetFieldID $I @($I, $I, $I, $I)
    GetStaticFieldID = Get-Jni GetStaticFieldID $I @($I, $I, $I, $I)
    NewObjectA = Get-Jni NewObjectA $I @($I, $I, $I, $I)
    NewStringUTF = Get-Jni NewStringUTF $I @($I, $I)
    GetStringUTFChars = Get-Jni GetStringUTFChars $I @($I, $I, $I)
    ReleaseStringUTFChars = Get-Jni ReleaseStringUTFChars ([void]) @($I, $I, $I)
    NewGlobalRef = Get-Jni NewGlobalRef $I @($I, $I)
    DeleteGlobalRef = Get-Jni DeleteGlobalRef ([void]) @($I, $I)
    DeleteLocalRef = Get-Jni DeleteLocalRef ([void]) @($I, $I)
    GetStaticObjectField = Get-Jni GetStaticObjectField $I @($I, $I, $I)
    GetStaticIntField = Get-Jni GetStaticIntField ([int]) @($I, $I, $I)
    CallObjectMethodA = Get-Jni CallObjectMethodA $I @($I, $I, $I, $I)
    CallVoidMethodA = Get-Jni CallVoidMethodA ([void]) @($I, $I, $I, $I)
    CallIntMethodA = Get-Jni CallIntMethodA ([int]) @($I, $I, $I, $I)
    CallBooleanMethodA = Get-Jni CallBooleanMethodA ([byte]) @($I, $I, $I, $I)
    CallStaticObjectMethodA = Get-Jni CallStaticObjectMethodA $I @($I, $I, $I, $I)
    CallStaticVoidMethodA = Get-Jni CallStaticVoidMethodA ([void]) @($I, $I, $I, $I)
}

function global:Assert-NoJavaException([string] $Step) {
    if ($global:Jni.ExceptionCheck.Invoke($global:JniEnv) -ne 0) {
        $global:Jni.ExceptionDescribe.Invoke($global:JniEnv); $global:Jni.ExceptionClear.Invoke($global:JniEnv)
        throw "Java exception at $Step"
    }
}
function global:Use-Utf8([string[]] $Text, [scriptblock] $Body) {
    $ptrs = @(foreach ($t in $Text) { $global:JniM::StringToCoTaskMemUTF8($t) })
    try { & $Body @ptrs } finally { foreach ($q in $ptrs) { $global:JniM::FreeCoTaskMem($q) } }
}
function global:Get-JClass([string] $Name) {
    $r = Use-Utf8 $Name { param($n) $global:Jni.FindClass.Invoke($global:JniEnv, $n) }
    Assert-NoJavaException $Name; [IntPtr]$r
}
function global:Get-JMethod([IntPtr] $Class, [string] $Name, [string] $Signature, [switch] $Static) {
    $f = if ($Static) { $global:Jni.GetStaticMethodID } else { $global:Jni.GetMethodID }
    $r = Use-Utf8 $Name, $Signature { param($n, $s) $f.Invoke($global:JniEnv, $Class, $n, $s) }
    Assert-NoJavaException "$Name$Signature"; [IntPtr]$r
}
function global:Get-JField([IntPtr] $Class, [string] $Name, [string] $Signature, [switch] $Static) {
    $f = if ($Static) { $global:Jni.GetStaticFieldID } else { $global:Jni.GetFieldID }
    $r = Use-Utf8 $Name, $Signature { param($n, $s) $f.Invoke($global:JniEnv, $Class, $n, $s) }
    Assert-NoJavaException "$Name$Signature"; [IntPtr]$r
}
function global:New-JString([string] $Text) {
    $r = Use-Utf8 $Text { param($t) $global:Jni.NewStringUTF.Invoke($global:JniEnv, $t) }
    Assert-NoJavaException 'NewStringUTF'; [IntPtr]$r
}
function global:ConvertFrom-JString([IntPtr] $JString) {
    $chars = $global:Jni.GetStringUTFChars.Invoke($global:JniEnv, $JString, [IntPtr]::Zero); Assert-NoJavaException 'GetStringUTFChars'
    try { $global:JniM::PtrToStringUTF8($chars) } finally { $global:Jni.ReleaseStringUTFChars.Invoke($global:JniEnv, $JString, $chars) }
}
# Calls a JNI function whose last parameter is a jvalue[]; arguments are
# written by their .NET type (int, long, float, double, bool, IntPtr).
function global:Invoke-JniA([Delegate] $Function, [IntPtr] $Target, [IntPtr] $Method, [object[]] $Arguments = @()) {
    $values = $global:JniM::AllocHGlobal([Math]::Max(8, 8 * $Arguments.Count))
    try {
        for ($i = 0; $i -lt $Arguments.Count; $i++) {
            $o = 8 * $i; $a = $Arguments[$i]; $global:JniM::WriteInt64($values, $o, 0)
            switch ($a) {
                { $_ -is [int] } { $global:JniM::WriteInt32($values, $o, $a); break }
                { $_ -is [long] } { $global:JniM::WriteInt64($values, $o, $a); break }
                { $_ -is [float] } { $global:JniM::WriteInt32($values, $o, [BitConverter]::SingleToInt32Bits($a)); break }
                { $_ -is [double] } { $global:JniM::WriteInt64($values, $o, [BitConverter]::DoubleToInt64Bits($a)); break }
                { $_ -is [bool] } { $global:JniM::WriteByte($values, $o, [byte]$a); break }
                { $_ -is [IntPtr] } { $global:JniM::WriteIntPtr($values, $o, $a); break }
                default { throw "No jvalue mapping for $($a.GetType().FullName)." }
            }
        }
        $r = $Function.Invoke($global:JniEnv, $Target, $Method, $values)
        Assert-NoJavaException 'Call'
        $r
    }
    finally { $global:JniM::FreeHGlobal($values) }
}
# ARGB as the signed int Android's color APIs take.
function global:ConvertTo-ArgbInt([byte] $R, [byte] $G, [byte] $B, [byte] $A = 255) { [BitConverter]::ToInt32([byte[]]@($B, $G, $R, $A), 0) }